# # run MULTIPLE containers together coz app needs more than one service:
                              # FastAPI server,   PostgreSQL database
# manage them together

services:
  app:
    build: .
    container_name: kipaji_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SCHEMA: ${SCHEMA}
    volumes:
      - ./static:/app/static      # for live updates during dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:


# Docker Compose
#      │
#      ├── app container (FastAPI)
#      │
#      └── db container (PostgreSQL)